name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Go to lib folder
      run: cd lib
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
